version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hackathon-ai-content"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rnm7a1bzjh3g"
s3_prefix = "hackathon-ai-content"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
